### ISSUE TITLE
Add alternative I2C address as parameter for the begin() method

### ISSUE THREAD

**Issue by jbaumann** [adafruit/Adafruit_AHTX0#7]
The quality of the AHTX0 library is very good, but it is currently not possible to change the I2C address of the sensor to 0x39. By adding an additional parameter to the begin() method (with a default to guarantee compatibility) this can be solved with minimal effort.

**Comment by ladyada** [comment]
when is the address 0x39? a PR to allow alternate addresses would be welcome!

**Comment by jbaumann** [comment]
With pleasure. I will prepare the PR in the next days.

**Comment by ladyada** [comment]
done!
